// biome-ignore-all format: generated
// This file is auto-generated by kitcn
// Do not edit manually. Run `kitcn codegen` to regenerate.

import { createApiLeaf, createGeneratedFunctionReference } from "kitcn/server";
import type { inferApiInputs, inferApiOutputs } from "kitcn/server";

import type { InferInsertModel, InferSelectModel } from "kitcn/orm";
import type { httpRouter } from "../functions/http";
import type { tables } from "../functions/schema";

export const api = {
  admin: {
    getSystemMetrics: createApiLeaf<"query", typeof import("../functions/admin").getSystemMetrics>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/admin").getSystemMetrics>("admin:getSystemMetrics"), { auth: "required", type: "query" }),
  },
  emailRoutes: {
    webhook: createApiLeaf<"mutation", typeof import("../functions/emailRoutes").webhook>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/emailRoutes").webhook>("emailRoutes:webhook"), { type: "mutation" }),
  },
  feedback: {
    create: createApiLeaf<"mutation", typeof import("../functions/feedback").create>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/feedback").create>("feedback:create"), { auth: "required", type: "mutation" }),
    getByIds: createApiLeaf<"query", typeof import("../functions/feedback").getByIds>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/feedback").getByIds>("feedback:getByIds"), { auth: "optional", type: "query" }),
    getBySlug: createApiLeaf<"query", typeof import("../functions/feedback").getBySlug>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/feedback").getBySlug>("feedback:getBySlug"), { auth: "optional", type: "query" }),
    getBySlugMeta: createApiLeaf<"query", typeof import("../functions/feedback").getBySlugMeta>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/feedback").getBySlugMeta>("feedback:getBySlugMeta"), { auth: "optional", type: "query" }),
    getDetailCritical: createApiLeaf<"query", typeof import("../functions/feedback").getDetailCritical>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/feedback").getDetailCritical>("feedback:getDetailCritical"), { auth: "optional", type: "query" }),
    getDetailInteractive: createApiLeaf<"query", typeof import("../functions/feedback").getDetailInteractive>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/feedback").getDetailInteractive>("feedback:getDetailInteractive"), { auth: "optional", type: "query" }),
    getMiddleComments: createApiLeaf<"query", typeof import("../functions/feedback").getMiddleComments>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/feedback").getMiddleComments>("feedback:getMiddleComments"), { auth: "optional", type: "query" }),
    listProjectFeedback: createApiLeaf<"query", typeof import("../functions/feedback").listProjectFeedback>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/feedback").listProjectFeedback>("feedback:listProjectFeedback"), { auth: "optional", limit: 50, type: "query" }),
    remove: createApiLeaf<"mutation", typeof import("../functions/feedback").remove>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/feedback").remove>("feedback:remove"), { auth: "required", type: "mutation" }),
    searchForLinking: createApiLeaf<"query", typeof import("../functions/feedback").searchForLinking>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/feedback").searchForLinking>("feedback:searchForLinking"), { auth: "optional", type: "query" }),
    setAnswerComment: createApiLeaf<"mutation", typeof import("../functions/feedback").setAnswerComment>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/feedback").setAnswerComment>("feedback:setAnswerComment"), { auth: "required", type: "mutation" }),
    updateAssigned: createApiLeaf<"mutation", typeof import("../functions/feedback").updateAssigned>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/feedback").updateAssigned>("feedback:updateAssigned"), { auth: "required", type: "mutation" }),
    updateBoard: createApiLeaf<"mutation", typeof import("../functions/feedback").updateBoard>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/feedback").updateBoard>("feedback:updateBoard"), { auth: "required", type: "mutation" }),
    updateStatus: createApiLeaf<"mutation", typeof import("../functions/feedback").updateStatus>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/feedback").updateStatus>("feedback:updateStatus"), { auth: "required", type: "mutation" }),
    updateTarget: createApiLeaf<"mutation", typeof import("../functions/feedback").updateTarget>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/feedback").updateTarget>("feedback:updateTarget"), { auth: "required", type: "mutation" }),
    updateTitle: createApiLeaf<"mutation", typeof import("../functions/feedback").updateTitle>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/feedback").updateTitle>("feedback:updateTitle"), { auth: "required", type: "mutation" }),
  },
  feedbackBoard: {
    create: createApiLeaf<"mutation", typeof import("../functions/feedbackBoard").create>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/feedbackBoard").create>("feedbackBoard:create"), { auth: "required", type: "mutation" }),
    get: createApiLeaf<"query", typeof import("../functions/feedbackBoard").get>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/feedbackBoard").get>("feedbackBoard:get"), { auth: "optional", type: "query" }),
    listProjectBoards: createApiLeaf<"query", typeof import("../functions/feedbackBoard").listProjectBoards>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/feedbackBoard").listProjectBoards>("feedbackBoard:listProjectBoards"), { auth: "optional", type: "query" }),
    remove: createApiLeaf<"mutation", typeof import("../functions/feedbackBoard").remove>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/feedbackBoard").remove>("feedbackBoard:remove"), { auth: "required", type: "mutation" }),
    update: createApiLeaf<"mutation", typeof import("../functions/feedbackBoard").update>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/feedbackBoard").update>("feedbackBoard:update"), { auth: "required", type: "mutation" }),
  },
  feedbackComment: {
    create: createApiLeaf<"mutation", typeof import("../functions/feedbackComment").create>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/feedbackComment").create>("feedbackComment:create"), { auth: "required", type: "mutation" }),
    listByFeedback: createApiLeaf<"query", typeof import("../functions/feedbackComment").listByFeedback>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/feedbackComment").listByFeedback>("feedbackComment:listByFeedback"), { auth: "optional", type: "query" }),
    remove: createApiLeaf<"mutation", typeof import("../functions/feedbackComment").remove>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/feedbackComment").remove>("feedbackComment:remove"), { auth: "required", type: "mutation" }),
    update: createApiLeaf<"mutation", typeof import("../functions/feedbackComment").update>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/feedbackComment").update>("feedbackComment:update"), { auth: "required", type: "mutation" }),
  },
  feedbackCommentEmote: {
    toggle: createApiLeaf<"mutation", typeof import("../functions/feedbackCommentEmote").toggle>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/feedbackCommentEmote").toggle>("feedbackCommentEmote:toggle"), { auth: "required", type: "mutation" }),
  },
  feedbackEvent: {
    listByFeedback: createApiLeaf<"query", typeof import("../functions/feedbackEvent").listByFeedback>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/feedbackEvent").listByFeedback>("feedbackEvent:listByFeedback"), { auth: "optional", type: "query" }),
  },
  feedbackGithub: {
    connectExisting: createApiLeaf<"action", typeof import("../functions/feedbackGithub").connectExisting>(createGeneratedFunctionReference<"action", "public", typeof import("../functions/feedbackGithub").connectExisting>("feedbackGithub:connectExisting"), { auth: "required", type: "action" }),
    createAndConnect: createApiLeaf<"action", typeof import("../functions/feedbackGithub").createAndConnect>(createGeneratedFunctionReference<"action", "public", typeof import("../functions/feedbackGithub").createAndConnect>("feedbackGithub:createAndConnect"), { auth: "required", type: "action" }),
    getAvailability: createApiLeaf<"query", typeof import("../functions/feedbackGithub").getAvailability>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/feedbackGithub").getAvailability>("feedbackGithub:getAvailability"), { auth: "required", type: "query" }),
    listByFeedback: createApiLeaf<"query", typeof import("../functions/feedbackGithub").listByFeedback>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/feedbackGithub").listByFeedback>("feedbackGithub:listByFeedback"), { auth: "optional", type: "query" }),
    refreshCounts: createApiLeaf<"action", typeof import("../functions/feedbackGithub").refreshCounts>(createGeneratedFunctionReference<"action", "public", typeof import("../functions/feedbackGithub").refreshCounts>("feedbackGithub:refreshCounts"), { auth: "required", type: "action" }),
    searchTargets: createApiLeaf<"action", typeof import("../functions/feedbackGithub").searchTargets>(createGeneratedFunctionReference<"action", "public", typeof import("../functions/feedbackGithub").searchTargets>("feedbackGithub:searchTargets"), { auth: "required", type: "action" }),
  },
  feedbackUpvote: {
    getCount: createApiLeaf<"query", typeof import("../functions/feedbackUpvote").getCount>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/feedbackUpvote").getCount>("feedbackUpvote:getCount"), { auth: "optional", type: "query" }),
    getUpvoteData: createApiLeaf<"query", typeof import("../functions/feedbackUpvote").getUpvoteData>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/feedbackUpvote").getUpvoteData>("feedbackUpvote:getUpvoteData"), { auth: "optional", type: "query" }),
    hasUpvoted: createApiLeaf<"query", typeof import("../functions/feedbackUpvote").hasUpvoted>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/feedbackUpvote").hasUpvoted>("feedbackUpvote:hasUpvoted"), { auth: "optional", type: "query" }),
    toggle: createApiLeaf<"mutation", typeof import("../functions/feedbackUpvote").toggle>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/feedbackUpvote").toggle>("feedbackUpvote:toggle"), { auth: "required", type: "mutation" }),
  },
  github: {
    disconnectRepository: createApiLeaf<"mutation", typeof import("../functions/github").disconnectRepository>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/github").disconnectRepository>("github:disconnectRepository"), { auth: "required", type: "mutation" }),
    getOrgIntegration: createApiLeaf<"query", typeof import("../functions/github").getOrgIntegration>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/github").getOrgIntegration>("github:getOrgIntegration"), { auth: "required", type: "query" }),
    getProjectIntegration: createApiLeaf<"query", typeof import("../functions/github").getProjectIntegration>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/github").getProjectIntegration>("github:getProjectIntegration"), { auth: "required", type: "query" }),
    startInstallationRefresh: createApiLeaf<"mutation", typeof import("../functions/github").startInstallationRefresh>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/github").startInstallationRefresh>("github:startInstallationRefresh"), { auth: "required", type: "mutation" }),
    startOrgConnection: createApiLeaf<"mutation", typeof import("../functions/github").startOrgConnection>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/github").startOrgConnection>("github:startOrgConnection"), { auth: "required", type: "mutation" }),
    startOrgInstallationRefresh: createApiLeaf<"mutation", typeof import("../functions/github").startOrgInstallationRefresh>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/github").startOrgInstallationRefresh>("github:startOrgInstallationRefresh"), { auth: "required", type: "mutation" }),
    startProjectConnection: createApiLeaf<"mutation", typeof import("../functions/github").startProjectConnection>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/github").startProjectConnection>("github:startProjectConnection"), { auth: "required", type: "mutation" }),
  },
  githubExternal: {
    connectRepository: createApiLeaf<"action", typeof import("../functions/githubExternal").connectRepository>(createGeneratedFunctionReference<"action", "public", typeof import("../functions/githubExternal").connectRepository>("githubExternal:connectRepository"), { auth: "required", type: "action" }),
    listInstallationRepositoriesForProject: createApiLeaf<"action", typeof import("../functions/githubExternal").listInstallationRepositoriesForProject>(createGeneratedFunctionReference<"action", "public", typeof import("../functions/githubExternal").listInstallationRepositoriesForProject>("githubExternal:listInstallationRepositoriesForProject"), { auth: "required", type: "action" }),
  },
  githubRoutes: {
    callback: createApiLeaf<"query", typeof import("../functions/githubRoutes").callback>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/githubRoutes").callback>("githubRoutes:callback"), { type: "query" }),
    webhook: createApiLeaf<"mutation", typeof import("../functions/githubRoutes").webhook>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/githubRoutes").webhook>("githubRoutes:webhook"), { type: "mutation" }),
  },
  org: {
    create: createApiLeaf<"mutation", typeof import("../functions/org").create>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/org").create>("org:create"), { auth: "required", type: "mutation" }),
    findMyEditableOrgs: createApiLeaf<"query", typeof import("../functions/org").findMyEditableOrgs>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/org").findMyEditableOrgs>("org:findMyEditableOrgs"), { auth: "required", type: "query" }),
    findMyOrgs: createApiLeaf<"query", typeof import("../functions/org").findMyOrgs>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/org").findMyOrgs>("org:findMyOrgs"), { auth: "required", type: "query" }),
    generateAvatarUploadUrl: createApiLeaf<"mutation", typeof import("../functions/org").generateAvatarUploadUrl>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/org").generateAvatarUploadUrl>("org:generateAvatarUploadUrl"), { auth: "required", type: "mutation" }),
    getDetails: createApiLeaf<"query", typeof import("../functions/org").getDetails>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/org").getDetails>("org:getDetails"), { auth: "optional", type: "query" }),
    getMyPermission: createApiLeaf<"query", typeof import("../functions/org").getMyPermission>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/org").getMyPermission>("org:getMyPermission"), { auth: "required", type: "query" }),
    syncAvatarMetadata: createApiLeaf<"mutation", typeof import("../functions/org").syncAvatarMetadata>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/org").syncAvatarMetadata>("org:syncAvatarMetadata"), { auth: "required", type: "mutation" }),
    update: createApiLeaf<"mutation", typeof import("../functions/org").update>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/org").update>("org:update"), { auth: "required", type: "mutation" }),
  },
  orgMember: {
    cancelInvitation: createApiLeaf<"mutation", typeof import("../functions/orgMember").cancelInvitation>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/orgMember").cancelInvitation>("orgMember:cancelInvitation"), { auth: "required", type: "mutation" }),
    inviteMember: createApiLeaf<"mutation", typeof import("../functions/orgMember").inviteMember>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/orgMember").inviteMember>("orgMember:inviteMember"), { auth: "required", type: "mutation" }),
    leaveOrganization: createApiLeaf<"mutation", typeof import("../functions/orgMember").leaveOrganization>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/orgMember").leaveOrganization>("orgMember:leaveOrganization"), { auth: "required", type: "mutation" }),
    listMembers: createApiLeaf<"query", typeof import("../functions/orgMember").listMembers>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/orgMember").listMembers>("orgMember:listMembers"), { auth: "required", type: "query" }),
    listPendingInvitations: createApiLeaf<"query", typeof import("../functions/orgMember").listPendingInvitations>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/orgMember").listPendingInvitations>("orgMember:listPendingInvitations"), { auth: "required", type: "query" }),
    removeMember: createApiLeaf<"mutation", typeof import("../functions/orgMember").removeMember>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/orgMember").removeMember>("orgMember:removeMember"), { auth: "required", type: "mutation" }),
    updateMemberRole: createApiLeaf<"mutation", typeof import("../functions/orgMember").updateMemberRole>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/orgMember").updateMemberRole>("orgMember:updateMemberRole"), { auth: "required", type: "mutation" }),
  },
  profile: {
    findMyProfile: createApiLeaf<"query", typeof import("../functions/profile").findMyProfile>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/profile").findMyProfile>("profile:findMyProfile"), { auth: "required", type: "query" }),
    generateAvatarUploadUrl: createApiLeaf<"mutation", typeof import("../functions/profile").generateAvatarUploadUrl>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/profile").generateAvatarUploadUrl>("profile:generateAvatarUploadUrl"), { auth: "required", type: "mutation" }),
    getByUsername: createApiLeaf<"query", typeof import("../functions/profile").getByUsername>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/profile").getByUsername>("profile:getByUsername"), { auth: "optional", type: "query" }),
    syncMetadata: createApiLeaf<"mutation", typeof import("../functions/profile").syncMetadata>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/profile").syncMetadata>("profile:syncMetadata"), { auth: "required", type: "mutation" }),
    update: createApiLeaf<"mutation", typeof import("../functions/profile").update>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/profile").update>("profile:update"), { auth: "required", type: "mutation" }),
  },
  project: {
    create: createApiLeaf<"mutation", typeof import("../functions/project").create>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/project").create>("project:create"), { auth: "required", type: "mutation" }),
    getDetails: createApiLeaf<"query", typeof import("../functions/project").getDetails>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/project").getDetails>("project:getDetails"), { auth: "optional", type: "query" }),
    getManyByOrg: createApiLeaf<"query", typeof import("../functions/project").getManyByOrg>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/project").getManyByOrg>("project:getManyByOrg"), { auth: "optional", type: "query" }),
    update: createApiLeaf<"mutation", typeof import("../functions/project").update>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/project").update>("project:update"), { auth: "required", type: "mutation" }),
  },
  projectMember: {
    inviteProjectMember: createApiLeaf<"mutation", typeof import("../functions/projectMember").inviteProjectMember>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/projectMember").inviteProjectMember>("projectMember:inviteProjectMember"), { auth: "required", type: "mutation" }),
    listAssignableMembers: createApiLeaf<"query", typeof import("../functions/projectMember").listAssignableMembers>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/projectMember").listAssignableMembers>("projectMember:listAssignableMembers"), { auth: "required", type: "query" }),
    listProjectMembers: createApiLeaf<"query", typeof import("../functions/projectMember").listProjectMembers>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/projectMember").listProjectMembers>("projectMember:listProjectMembers"), { auth: "required", type: "query" }),
    removeProjectMember: createApiLeaf<"mutation", typeof import("../functions/projectMember").removeProjectMember>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/projectMember").removeProjectMember>("projectMember:removeProjectMember"), { auth: "required", type: "mutation" }),
  },
  update: {
    backfillProjectUpdatedTimes: createApiLeaf<"mutation", typeof import("../functions/update").backfillProjectUpdatedTimes>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/update").backfillProjectUpdatedTimes>("update:backfillProjectUpdatedTimes"), { auth: "required", type: "mutation" }),
    bulkPublish: createApiLeaf<"mutation", typeof import("../functions/update").bulkPublish>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/update").bulkPublish>("update:bulkPublish"), { auth: "required", type: "mutation" }),
    bulkRemove: createApiLeaf<"mutation", typeof import("../functions/update").bulkRemove>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/update").bulkRemove>("update:bulkRemove"), { auth: "required", type: "mutation" }),
    bulkUnpublish: createApiLeaf<"mutation", typeof import("../functions/update").bulkUnpublish>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/update").bulkUnpublish>("update:bulkUnpublish"), { auth: "required", type: "mutation" }),
    clearCoverImage: createApiLeaf<"mutation", typeof import("../functions/update").clearCoverImage>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/update").clearCoverImage>("update:clearCoverImage"), { auth: "required", type: "mutation" }),
    create: createApiLeaf<"mutation", typeof import("../functions/update").create>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/update").create>("update:create"), { auth: "required", type: "mutation" }),
    generateCoverImageUploadUrl: createApiLeaf<"mutation", typeof import("../functions/update").generateCoverImageUploadUrl>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/update").generateCoverImageUploadUrl>("update:generateCoverImageUploadUrl"), { auth: "required", type: "mutation" }),
    getBySlug: createApiLeaf<"query", typeof import("../functions/update").getBySlug>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/update").getBySlug>("update:getBySlug"), { auth: "optional", type: "query" }),
    getCoverImageUrl: createApiLeaf<"query", typeof import("../functions/update").getCoverImageUrl>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/update").getCoverImageUrl>("update:getCoverImageUrl"), { auth: "optional", type: "query" }),
    getDetailCritical: createApiLeaf<"query", typeof import("../functions/update").getDetailCritical>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/update").getDetailCritical>("update:getDetailCritical"), { auth: "optional", type: "query" }),
    getDetailInteractive: createApiLeaf<"query", typeof import("../functions/update").getDetailInteractive>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/update").getDetailInteractive>("update:getDetailInteractive"), { auth: "optional", type: "query" }),
    getMiddleComments: createApiLeaf<"query", typeof import("../functions/update").getMiddleComments>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/update").getMiddleComments>("update:getMiddleComments"), { auth: "optional", type: "query" }),
    listByProject: createApiLeaf<"query", typeof import("../functions/update").listByProject>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/update").listByProject>("update:listByProject"), { auth: "optional", limit: 10, type: "query" }),
    listProjectDashboard: createApiLeaf<"query", typeof import("../functions/update").listProjectDashboard>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/update").listProjectDashboard>("update:listProjectDashboard"), { auth: "required", limit: 50, type: "query" }),
    publish: createApiLeaf<"mutation", typeof import("../functions/update").publish>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/update").publish>("update:publish"), { auth: "required", type: "mutation" }),
    remove: createApiLeaf<"mutation", typeof import("../functions/update").remove>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/update").remove>("update:remove"), { auth: "required", type: "mutation" }),
    syncMetadata: createApiLeaf<"mutation", typeof import("../functions/update").syncMetadata>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/update").syncMetadata>("update:syncMetadata"), { auth: "required", type: "mutation" }),
    unpublish: createApiLeaf<"mutation", typeof import("../functions/update").unpublish>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/update").unpublish>("update:unpublish"), { auth: "required", type: "mutation" }),
    update: createApiLeaf<"mutation", typeof import("../functions/update").update>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/update").update>("update:update"), { auth: "required", type: "mutation" }),
  },
  updateComment: {
    create: createApiLeaf<"mutation", typeof import("../functions/updateComment").create>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/updateComment").create>("updateComment:create"), { auth: "required", type: "mutation" }),
    listByUpdate: createApiLeaf<"query", typeof import("../functions/updateComment").listByUpdate>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/updateComment").listByUpdate>("updateComment:listByUpdate"), { auth: "optional", type: "query" }),
    remove: createApiLeaf<"mutation", typeof import("../functions/updateComment").remove>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/updateComment").remove>("updateComment:remove"), { auth: "required", type: "mutation" }),
    update: createApiLeaf<"mutation", typeof import("../functions/updateComment").update>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/updateComment").update>("updateComment:update"), { auth: "required", type: "mutation" }),
  },
  updateCommentEmote: {
    toggle: createApiLeaf<"mutation", typeof import("../functions/updateCommentEmote").toggle>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/updateCommentEmote").toggle>("updateCommentEmote:toggle"), { auth: "required", type: "mutation" }),
  },
  updateEmote: {
    toggle: createApiLeaf<"mutation", typeof import("../functions/updateEmote").toggle>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/updateEmote").toggle>("updateEmote:toggle"), { auth: "required", type: "mutation" }),
  },
  userDataExport: {
    exportData: createApiLeaf<"query", typeof import("../functions/userDataExport").exportData>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/userDataExport").exportData>("userDataExport:exportData"), { auth: "required", type: "query" }),
    getAvailableSections: createApiLeaf<"query", typeof import("../functions/userDataExport").getAvailableSections>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/userDataExport").getAvailableSections>("userDataExport:getAvailableSections"), { auth: "required", type: "query" }),
  },
  http: undefined as unknown as typeof httpRouter,
  _http: {
  },
} as const;

export type Api = typeof api;
export type ApiInputs = inferApiInputs<Api>;
export type ApiOutputs = inferApiOutputs<Api>;

export type TableName = keyof typeof tables;
export type Select<T extends TableName> = InferSelectModel<(typeof tables)[T]>;
export type Insert<T extends TableName> = InferInsertModel<(typeof tables)[T]>;
