/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AtChar123orgChar125RouteRouteImport } from './routes/@{$org}/route'
import { Route as RouteRouteImport } from './routes/route'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as AtChar123orgChar125IndexRouteImport } from './routes/@{$org}/index'
import { Route as CreateAtlayoutRouteImport } from './routes/create/@layout'
import { Route as BlankSignOutRouteImport } from './routes/blank/sign-out'
import { Route as BlankSignInRouteImport } from './routes/blank/sign-in'
import { Route as Blank404RouteImport } from './routes/blank/404'
import { Route as AtChar123orgChar125SettingsRouteImport } from './routes/@{$org}/settings'
import { Route as AtChar123orgChar125ProjectRouteRouteImport } from './routes/@{$org}/$project/route'
import { Route as ProfileSettingsIndexRouteImport } from './routes/profile/settings/index'
import { Route as ProfileUsernameIndexRouteImport } from './routes/profile/$username/index'
import { Route as CreateTeamIndexRouteImport } from './routes/create/team/index'
import { Route as CreateProjectIndexRouteImport } from './routes/create/project/index'
import { Route as AtChar123orgChar125ProjectIndexRouteImport } from './routes/@{$org}/$project/index'
import { Route as AtChar123orgChar125ProjectUpdatesIndexRouteImport } from './routes/@{$org}/$project/updates/index'
import { Route as AtChar123orgChar125ProjectRoadmapIndexRouteImport } from './routes/@{$org}/$project/roadmap/index'
import { Route as AtChar123orgChar125ProjectFilesIndexRouteImport } from './routes/@{$org}/$project/files/index'
import { Route as AtChar123orgChar125ProjectFeedbackIndexRouteImport } from './routes/@{$org}/$project/feedback/index'
import { Route as AtChar123orgChar125ProjectDiscussionsIndexRouteImport } from './routes/@{$org}/$project/discussions/index'
import { Route as AtChar123orgChar125ProjectChatIndexRouteImport } from './routes/@{$org}/$project/chat/index'
import { Route as AtChar123orgChar125ProjectChatAtlayoutRouteImport } from './routes/@{$org}/$project/chat/@layout'
import { Route as AtChar123orgChar125ProjectFeedbackNewIndexRouteImport } from './routes/@{$org}/$project/feedback/new/index'
import { Route as AtChar123orgChar125ProjectFeedbackBoardsIndexRouteImport } from './routes/@{$org}/$project/feedback/boards/index'
import { Route as AtChar123orgChar125ProjectFeedbackFeedbackIdIndexRouteImport } from './routes/@{$org}/$project/feedback/$feedbackId/index'
import { Route as AtChar123orgChar125ProjectChatChatIdIndexRouteImport } from './routes/@{$org}/$project/chat/$chatId/index'
import { Route as AtChar123orgChar125ProjectFeedbackBoardNewRouteImport } from './routes/@{$org}/$project/feedback/board/new'
import { Route as AtChar123orgChar125ProjectFeedbackBoardBoardIndexRouteImport } from './routes/@{$org}/$project/feedback/board/$board/index'
import { Route as AtChar123orgChar125ProjectFeedbackBoardBoardEditRouteImport } from './routes/@{$org}/$project/feedback/board/$board/edit'
import { Route as AtChar123orgChar125ProjectFeedbackBoardBoardAtlayoutRouteImport } from './routes/@{$org}/$project/feedback/board/$board/@layout'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const AtChar123orgChar125RouteRoute =
  AtChar123orgChar125RouteRouteImport.update({
    id: '/@{$org}',
    path: '/@{$org}',
    getParentRoute: () => rootRouteImport,
  } as any)
const RouteRoute = RouteRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtChar123orgChar125IndexRoute =
  AtChar123orgChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AtChar123orgChar125RouteRoute,
  } as any)
const CreateAtlayoutRoute = CreateAtlayoutRouteImport.update({
  id: '/create/@layout',
  path: '/create/@layout',
  getParentRoute: () => rootRouteImport,
} as any)
const BlankSignOutRoute = BlankSignOutRouteImport.update({
  id: '/blank/sign-out',
  path: '/blank/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const BlankSignInRoute = BlankSignInRouteImport.update({
  id: '/blank/sign-in',
  path: '/blank/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const Blank404Route = Blank404RouteImport.update({
  id: '/blank/404',
  path: '/blank/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AtChar123orgChar125SettingsRoute =
  AtChar123orgChar125SettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AtChar123orgChar125RouteRoute,
  } as any)
const AtChar123orgChar125ProjectRouteRoute =
  AtChar123orgChar125ProjectRouteRouteImport.update({
    id: '/$project',
    path: '/$project',
    getParentRoute: () => AtChar123orgChar125RouteRoute,
  } as any)
const ProfileSettingsIndexRoute = ProfileSettingsIndexRouteImport.update({
  id: '/profile/settings/',
  path: '/profile/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameIndexRoute = ProfileUsernameIndexRouteImport.update({
  id: '/profile/$username/',
  path: '/profile/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTeamIndexRoute = CreateTeamIndexRouteImport.update({
  id: '/create/team/',
  path: '/create/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateProjectIndexRoute = CreateProjectIndexRouteImport.update({
  id: '/create/project/',
  path: '/create/project/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtChar123orgChar125ProjectIndexRoute =
  AtChar123orgChar125ProjectIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AtChar123orgChar125ProjectRouteRoute,
  } as any)
const AtChar123orgChar125ProjectUpdatesIndexRoute =
  AtChar123orgChar125ProjectUpdatesIndexRouteImport.update({
    id: '/updates/',
    path: '/updates/',
    getParentRoute: () => AtChar123orgChar125ProjectRouteRoute,
  } as any)
const AtChar123orgChar125ProjectRoadmapIndexRoute =
  AtChar123orgChar125ProjectRoadmapIndexRouteImport.update({
    id: '/roadmap/',
    path: '/roadmap/',
    getParentRoute: () => AtChar123orgChar125ProjectRouteRoute,
  } as any)
const AtChar123orgChar125ProjectFilesIndexRoute =
  AtChar123orgChar125ProjectFilesIndexRouteImport.update({
    id: '/files/',
    path: '/files/',
    getParentRoute: () => AtChar123orgChar125ProjectRouteRoute,
  } as any)
const AtChar123orgChar125ProjectFeedbackIndexRoute =
  AtChar123orgChar125ProjectFeedbackIndexRouteImport.update({
    id: '/feedback/',
    path: '/feedback/',
    getParentRoute: () => AtChar123orgChar125ProjectRouteRoute,
  } as any)
const AtChar123orgChar125ProjectDiscussionsIndexRoute =
  AtChar123orgChar125ProjectDiscussionsIndexRouteImport.update({
    id: '/discussions/',
    path: '/discussions/',
    getParentRoute: () => AtChar123orgChar125ProjectRouteRoute,
  } as any)
const AtChar123orgChar125ProjectChatIndexRoute =
  AtChar123orgChar125ProjectChatIndexRouteImport.update({
    id: '/chat/',
    path: '/chat/',
    getParentRoute: () => AtChar123orgChar125ProjectRouteRoute,
  } as any)
const AtChar123orgChar125ProjectChatAtlayoutRoute =
  AtChar123orgChar125ProjectChatAtlayoutRouteImport.update({
    id: '/chat/@layout',
    path: '/chat/@layout',
    getParentRoute: () => AtChar123orgChar125ProjectRouteRoute,
  } as any)
const AtChar123orgChar125ProjectFeedbackNewIndexRoute =
  AtChar123orgChar125ProjectFeedbackNewIndexRouteImport.update({
    id: '/feedback/new/',
    path: '/feedback/new/',
    getParentRoute: () => AtChar123orgChar125ProjectRouteRoute,
  } as any)
const AtChar123orgChar125ProjectFeedbackBoardsIndexRoute =
  AtChar123orgChar125ProjectFeedbackBoardsIndexRouteImport.update({
    id: '/feedback/boards/',
    path: '/feedback/boards/',
    getParentRoute: () => AtChar123orgChar125ProjectRouteRoute,
  } as any)
const AtChar123orgChar125ProjectFeedbackFeedbackIdIndexRoute =
  AtChar123orgChar125ProjectFeedbackFeedbackIdIndexRouteImport.update({
    id: '/feedback/$feedbackId/',
    path: '/feedback/$feedbackId/',
    getParentRoute: () => AtChar123orgChar125ProjectRouteRoute,
  } as any)
const AtChar123orgChar125ProjectChatChatIdIndexRoute =
  AtChar123orgChar125ProjectChatChatIdIndexRouteImport.update({
    id: '/chat/$chatId/',
    path: '/chat/$chatId/',
    getParentRoute: () => AtChar123orgChar125ProjectRouteRoute,
  } as any)
const AtChar123orgChar125ProjectFeedbackBoardNewRoute =
  AtChar123orgChar125ProjectFeedbackBoardNewRouteImport.update({
    id: '/feedback/board/new',
    path: '/feedback/board/new',
    getParentRoute: () => AtChar123orgChar125ProjectRouteRoute,
  } as any)
const AtChar123orgChar125ProjectFeedbackBoardBoardIndexRoute =
  AtChar123orgChar125ProjectFeedbackBoardBoardIndexRouteImport.update({
    id: '/feedback/board/$board/',
    path: '/feedback/board/$board/',
    getParentRoute: () => AtChar123orgChar125ProjectRouteRoute,
  } as any)
const AtChar123orgChar125ProjectFeedbackBoardBoardEditRoute =
  AtChar123orgChar125ProjectFeedbackBoardBoardEditRouteImport.update({
    id: '/feedback/board/$board/edit',
    path: '/feedback/board/$board/edit',
    getParentRoute: () => AtChar123orgChar125ProjectRouteRoute,
  } as any)
const AtChar123orgChar125ProjectFeedbackBoardBoardAtlayoutRoute =
  AtChar123orgChar125ProjectFeedbackBoardBoardAtlayoutRouteImport.update({
    id: '/feedback/board/$board/@layout',
    path: '/feedback/board/$board/@layout',
    getParentRoute: () => AtChar123orgChar125ProjectRouteRoute,
  } as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof RouteRoute
  '/@{$org}': typeof AtChar123orgChar125RouteRouteWithChildren
  '/@{$org}/$project': typeof AtChar123orgChar125ProjectRouteRouteWithChildren
  '/@{$org}/settings': typeof AtChar123orgChar125SettingsRoute
  '/blank/404': typeof Blank404Route
  '/blank/sign-in': typeof BlankSignInRoute
  '/blank/sign-out': typeof BlankSignOutRoute
  '/create/@layout': typeof CreateAtlayoutRoute
  '/@{$org}/': typeof AtChar123orgChar125IndexRoute
  '/settings': typeof SettingsIndexRoute
  '/@{$org}/$project/': typeof AtChar123orgChar125ProjectIndexRoute
  '/create/project': typeof CreateProjectIndexRoute
  '/create/team': typeof CreateTeamIndexRoute
  '/profile/$username': typeof ProfileUsernameIndexRoute
  '/profile/settings': typeof ProfileSettingsIndexRoute
  '/@{$org}/$project/chat/@layout': typeof AtChar123orgChar125ProjectChatAtlayoutRoute
  '/@{$org}/$project/chat': typeof AtChar123orgChar125ProjectChatIndexRoute
  '/@{$org}/$project/discussions': typeof AtChar123orgChar125ProjectDiscussionsIndexRoute
  '/@{$org}/$project/feedback': typeof AtChar123orgChar125ProjectFeedbackIndexRoute
  '/@{$org}/$project/files': typeof AtChar123orgChar125ProjectFilesIndexRoute
  '/@{$org}/$project/roadmap': typeof AtChar123orgChar125ProjectRoadmapIndexRoute
  '/@{$org}/$project/updates': typeof AtChar123orgChar125ProjectUpdatesIndexRoute
  '/@{$org}/$project/feedback/board/new': typeof AtChar123orgChar125ProjectFeedbackBoardNewRoute
  '/@{$org}/$project/chat/$chatId': typeof AtChar123orgChar125ProjectChatChatIdIndexRoute
  '/@{$org}/$project/feedback/$feedbackId': typeof AtChar123orgChar125ProjectFeedbackFeedbackIdIndexRoute
  '/@{$org}/$project/feedback/boards': typeof AtChar123orgChar125ProjectFeedbackBoardsIndexRoute
  '/@{$org}/$project/feedback/new': typeof AtChar123orgChar125ProjectFeedbackNewIndexRoute
  '/@{$org}/$project/feedback/board/$board/@layout': typeof AtChar123orgChar125ProjectFeedbackBoardBoardAtlayoutRoute
  '/@{$org}/$project/feedback/board/$board/edit': typeof AtChar123orgChar125ProjectFeedbackBoardBoardEditRoute
  '/@{$org}/$project/feedback/board/$board': typeof AtChar123orgChar125ProjectFeedbackBoardBoardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof RouteRoute
  '/@{$org}/settings': typeof AtChar123orgChar125SettingsRoute
  '/blank/404': typeof Blank404Route
  '/blank/sign-in': typeof BlankSignInRoute
  '/blank/sign-out': typeof BlankSignOutRoute
  '/create/@layout': typeof CreateAtlayoutRoute
  '/@{$org}': typeof AtChar123orgChar125IndexRoute
  '/settings': typeof SettingsIndexRoute
  '/@{$org}/$project': typeof AtChar123orgChar125ProjectIndexRoute
  '/create/project': typeof CreateProjectIndexRoute
  '/create/team': typeof CreateTeamIndexRoute
  '/profile/$username': typeof ProfileUsernameIndexRoute
  '/profile/settings': typeof ProfileSettingsIndexRoute
  '/@{$org}/$project/chat/@layout': typeof AtChar123orgChar125ProjectChatAtlayoutRoute
  '/@{$org}/$project/chat': typeof AtChar123orgChar125ProjectChatIndexRoute
  '/@{$org}/$project/discussions': typeof AtChar123orgChar125ProjectDiscussionsIndexRoute
  '/@{$org}/$project/feedback': typeof AtChar123orgChar125ProjectFeedbackIndexRoute
  '/@{$org}/$project/files': typeof AtChar123orgChar125ProjectFilesIndexRoute
  '/@{$org}/$project/roadmap': typeof AtChar123orgChar125ProjectRoadmapIndexRoute
  '/@{$org}/$project/updates': typeof AtChar123orgChar125ProjectUpdatesIndexRoute
  '/@{$org}/$project/feedback/board/new': typeof AtChar123orgChar125ProjectFeedbackBoardNewRoute
  '/@{$org}/$project/chat/$chatId': typeof AtChar123orgChar125ProjectChatChatIdIndexRoute
  '/@{$org}/$project/feedback/$feedbackId': typeof AtChar123orgChar125ProjectFeedbackFeedbackIdIndexRoute
  '/@{$org}/$project/feedback/boards': typeof AtChar123orgChar125ProjectFeedbackBoardsIndexRoute
  '/@{$org}/$project/feedback/new': typeof AtChar123orgChar125ProjectFeedbackNewIndexRoute
  '/@{$org}/$project/feedback/board/$board/@layout': typeof AtChar123orgChar125ProjectFeedbackBoardBoardAtlayoutRoute
  '/@{$org}/$project/feedback/board/$board/edit': typeof AtChar123orgChar125ProjectFeedbackBoardBoardEditRoute
  '/@{$org}/$project/feedback/board/$board': typeof AtChar123orgChar125ProjectFeedbackBoardBoardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof RouteRoute
  '/@{$org}': typeof AtChar123orgChar125RouteRouteWithChildren
  '/@{$org}/$project': typeof AtChar123orgChar125ProjectRouteRouteWithChildren
  '/@{$org}/settings': typeof AtChar123orgChar125SettingsRoute
  '/blank/404': typeof Blank404Route
  '/blank/sign-in': typeof BlankSignInRoute
  '/blank/sign-out': typeof BlankSignOutRoute
  '/create/@layout': typeof CreateAtlayoutRoute
  '/@{$org}/': typeof AtChar123orgChar125IndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/@{$org}/$project/': typeof AtChar123orgChar125ProjectIndexRoute
  '/create/project/': typeof CreateProjectIndexRoute
  '/create/team/': typeof CreateTeamIndexRoute
  '/profile/$username/': typeof ProfileUsernameIndexRoute
  '/profile/settings/': typeof ProfileSettingsIndexRoute
  '/@{$org}/$project/chat/@layout': typeof AtChar123orgChar125ProjectChatAtlayoutRoute
  '/@{$org}/$project/chat/': typeof AtChar123orgChar125ProjectChatIndexRoute
  '/@{$org}/$project/discussions/': typeof AtChar123orgChar125ProjectDiscussionsIndexRoute
  '/@{$org}/$project/feedback/': typeof AtChar123orgChar125ProjectFeedbackIndexRoute
  '/@{$org}/$project/files/': typeof AtChar123orgChar125ProjectFilesIndexRoute
  '/@{$org}/$project/roadmap/': typeof AtChar123orgChar125ProjectRoadmapIndexRoute
  '/@{$org}/$project/updates/': typeof AtChar123orgChar125ProjectUpdatesIndexRoute
  '/@{$org}/$project/feedback/board/new': typeof AtChar123orgChar125ProjectFeedbackBoardNewRoute
  '/@{$org}/$project/chat/$chatId/': typeof AtChar123orgChar125ProjectChatChatIdIndexRoute
  '/@{$org}/$project/feedback/$feedbackId/': typeof AtChar123orgChar125ProjectFeedbackFeedbackIdIndexRoute
  '/@{$org}/$project/feedback/boards/': typeof AtChar123orgChar125ProjectFeedbackBoardsIndexRoute
  '/@{$org}/$project/feedback/new/': typeof AtChar123orgChar125ProjectFeedbackNewIndexRoute
  '/@{$org}/$project/feedback/board/$board/@layout': typeof AtChar123orgChar125ProjectFeedbackBoardBoardAtlayoutRoute
  '/@{$org}/$project/feedback/board/$board/edit': typeof AtChar123orgChar125ProjectFeedbackBoardBoardEditRoute
  '/@{$org}/$project/feedback/board/$board/': typeof AtChar123orgChar125ProjectFeedbackBoardBoardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/@{$org}'
    | '/@{$org}/$project'
    | '/@{$org}/settings'
    | '/blank/404'
    | '/blank/sign-in'
    | '/blank/sign-out'
    | '/create/@layout'
    | '/@{$org}/'
    | '/settings'
    | '/@{$org}/$project/'
    | '/create/project'
    | '/create/team'
    | '/profile/$username'
    | '/profile/settings'
    | '/@{$org}/$project/chat/@layout'
    | '/@{$org}/$project/chat'
    | '/@{$org}/$project/discussions'
    | '/@{$org}/$project/feedback'
    | '/@{$org}/$project/files'
    | '/@{$org}/$project/roadmap'
    | '/@{$org}/$project/updates'
    | '/@{$org}/$project/feedback/board/new'
    | '/@{$org}/$project/chat/$chatId'
    | '/@{$org}/$project/feedback/$feedbackId'
    | '/@{$org}/$project/feedback/boards'
    | '/@{$org}/$project/feedback/new'
    | '/@{$org}/$project/feedback/board/$board/@layout'
    | '/@{$org}/$project/feedback/board/$board/edit'
    | '/@{$org}/$project/feedback/board/$board'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/@{$org}/settings'
    | '/blank/404'
    | '/blank/sign-in'
    | '/blank/sign-out'
    | '/create/@layout'
    | '/@{$org}'
    | '/settings'
    | '/@{$org}/$project'
    | '/create/project'
    | '/create/team'
    | '/profile/$username'
    | '/profile/settings'
    | '/@{$org}/$project/chat/@layout'
    | '/@{$org}/$project/chat'
    | '/@{$org}/$project/discussions'
    | '/@{$org}/$project/feedback'
    | '/@{$org}/$project/files'
    | '/@{$org}/$project/roadmap'
    | '/@{$org}/$project/updates'
    | '/@{$org}/$project/feedback/board/new'
    | '/@{$org}/$project/chat/$chatId'
    | '/@{$org}/$project/feedback/$feedbackId'
    | '/@{$org}/$project/feedback/boards'
    | '/@{$org}/$project/feedback/new'
    | '/@{$org}/$project/feedback/board/$board/@layout'
    | '/@{$org}/$project/feedback/board/$board/edit'
    | '/@{$org}/$project/feedback/board/$board'
  id:
    | '__root__'
    | '/'
    | '/@{$org}'
    | '/@{$org}/$project'
    | '/@{$org}/settings'
    | '/blank/404'
    | '/blank/sign-in'
    | '/blank/sign-out'
    | '/create/@layout'
    | '/@{$org}/'
    | '/settings/'
    | '/@{$org}/$project/'
    | '/create/project/'
    | '/create/team/'
    | '/profile/$username/'
    | '/profile/settings/'
    | '/@{$org}/$project/chat/@layout'
    | '/@{$org}/$project/chat/'
    | '/@{$org}/$project/discussions/'
    | '/@{$org}/$project/feedback/'
    | '/@{$org}/$project/files/'
    | '/@{$org}/$project/roadmap/'
    | '/@{$org}/$project/updates/'
    | '/@{$org}/$project/feedback/board/new'
    | '/@{$org}/$project/chat/$chatId/'
    | '/@{$org}/$project/feedback/$feedbackId/'
    | '/@{$org}/$project/feedback/boards/'
    | '/@{$org}/$project/feedback/new/'
    | '/@{$org}/$project/feedback/board/$board/@layout'
    | '/@{$org}/$project/feedback/board/$board/edit'
    | '/@{$org}/$project/feedback/board/$board/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RouteRoute: typeof RouteRoute
  AtChar123orgChar125RouteRoute: typeof AtChar123orgChar125RouteRouteWithChildren
  Blank404Route: typeof Blank404Route
  BlankSignInRoute: typeof BlankSignInRoute
  BlankSignOutRoute: typeof BlankSignOutRoute
  CreateAtlayoutRoute: typeof CreateAtlayoutRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  CreateProjectIndexRoute: typeof CreateProjectIndexRoute
  CreateTeamIndexRoute: typeof CreateTeamIndexRoute
  ProfileUsernameIndexRoute: typeof ProfileUsernameIndexRoute
  ProfileSettingsIndexRoute: typeof ProfileSettingsIndexRoute
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$'
  id: '__root__' | '/api/auth/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/@{$org}': {
      id: '/@{$org}'
      path: '/@{$org}'
      fullPath: '/@{$org}'
      preLoaderRoute: typeof AtChar123orgChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@{$org}/': {
      id: '/@{$org}/'
      path: '/'
      fullPath: '/@{$org}/'
      preLoaderRoute: typeof AtChar123orgChar125IndexRouteImport
      parentRoute: typeof AtChar123orgChar125RouteRoute
    }
    '/create/@layout': {
      id: '/create/@layout'
      path: '/create/@layout'
      fullPath: '/create/@layout'
      preLoaderRoute: typeof CreateAtlayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blank/sign-out': {
      id: '/blank/sign-out'
      path: '/blank/sign-out'
      fullPath: '/blank/sign-out'
      preLoaderRoute: typeof BlankSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blank/sign-in': {
      id: '/blank/sign-in'
      path: '/blank/sign-in'
      fullPath: '/blank/sign-in'
      preLoaderRoute: typeof BlankSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blank/404': {
      id: '/blank/404'
      path: '/blank/404'
      fullPath: '/blank/404'
      preLoaderRoute: typeof Blank404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@{$org}/settings': {
      id: '/@{$org}/settings'
      path: '/settings'
      fullPath: '/@{$org}/settings'
      preLoaderRoute: typeof AtChar123orgChar125SettingsRouteImport
      parentRoute: typeof AtChar123orgChar125RouteRoute
    }
    '/@{$org}/$project': {
      id: '/@{$org}/$project'
      path: '/$project'
      fullPath: '/@{$org}/$project'
      preLoaderRoute: typeof AtChar123orgChar125ProjectRouteRouteImport
      parentRoute: typeof AtChar123orgChar125RouteRoute
    }
    '/profile/settings/': {
      id: '/profile/settings/'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username/': {
      id: '/profile/$username/'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/team/': {
      id: '/create/team/'
      path: '/create/team'
      fullPath: '/create/team'
      preLoaderRoute: typeof CreateTeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/project/': {
      id: '/create/project/'
      path: '/create/project'
      fullPath: '/create/project'
      preLoaderRoute: typeof CreateProjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@{$org}/$project/': {
      id: '/@{$org}/$project/'
      path: '/'
      fullPath: '/@{$org}/$project/'
      preLoaderRoute: typeof AtChar123orgChar125ProjectIndexRouteImport
      parentRoute: typeof AtChar123orgChar125ProjectRouteRoute
    }
    '/@{$org}/$project/updates/': {
      id: '/@{$org}/$project/updates/'
      path: '/updates'
      fullPath: '/@{$org}/$project/updates'
      preLoaderRoute: typeof AtChar123orgChar125ProjectUpdatesIndexRouteImport
      parentRoute: typeof AtChar123orgChar125ProjectRouteRoute
    }
    '/@{$org}/$project/roadmap/': {
      id: '/@{$org}/$project/roadmap/'
      path: '/roadmap'
      fullPath: '/@{$org}/$project/roadmap'
      preLoaderRoute: typeof AtChar123orgChar125ProjectRoadmapIndexRouteImport
      parentRoute: typeof AtChar123orgChar125ProjectRouteRoute
    }
    '/@{$org}/$project/files/': {
      id: '/@{$org}/$project/files/'
      path: '/files'
      fullPath: '/@{$org}/$project/files'
      preLoaderRoute: typeof AtChar123orgChar125ProjectFilesIndexRouteImport
      parentRoute: typeof AtChar123orgChar125ProjectRouteRoute
    }
    '/@{$org}/$project/feedback/': {
      id: '/@{$org}/$project/feedback/'
      path: '/feedback'
      fullPath: '/@{$org}/$project/feedback'
      preLoaderRoute: typeof AtChar123orgChar125ProjectFeedbackIndexRouteImport
      parentRoute: typeof AtChar123orgChar125ProjectRouteRoute
    }
    '/@{$org}/$project/discussions/': {
      id: '/@{$org}/$project/discussions/'
      path: '/discussions'
      fullPath: '/@{$org}/$project/discussions'
      preLoaderRoute: typeof AtChar123orgChar125ProjectDiscussionsIndexRouteImport
      parentRoute: typeof AtChar123orgChar125ProjectRouteRoute
    }
    '/@{$org}/$project/chat/': {
      id: '/@{$org}/$project/chat/'
      path: '/chat'
      fullPath: '/@{$org}/$project/chat'
      preLoaderRoute: typeof AtChar123orgChar125ProjectChatIndexRouteImport
      parentRoute: typeof AtChar123orgChar125ProjectRouteRoute
    }
    '/@{$org}/$project/chat/@layout': {
      id: '/@{$org}/$project/chat/@layout'
      path: '/chat/@layout'
      fullPath: '/@{$org}/$project/chat/@layout'
      preLoaderRoute: typeof AtChar123orgChar125ProjectChatAtlayoutRouteImport
      parentRoute: typeof AtChar123orgChar125ProjectRouteRoute
    }
    '/@{$org}/$project/feedback/new/': {
      id: '/@{$org}/$project/feedback/new/'
      path: '/feedback/new'
      fullPath: '/@{$org}/$project/feedback/new'
      preLoaderRoute: typeof AtChar123orgChar125ProjectFeedbackNewIndexRouteImport
      parentRoute: typeof AtChar123orgChar125ProjectRouteRoute
    }
    '/@{$org}/$project/feedback/boards/': {
      id: '/@{$org}/$project/feedback/boards/'
      path: '/feedback/boards'
      fullPath: '/@{$org}/$project/feedback/boards'
      preLoaderRoute: typeof AtChar123orgChar125ProjectFeedbackBoardsIndexRouteImport
      parentRoute: typeof AtChar123orgChar125ProjectRouteRoute
    }
    '/@{$org}/$project/feedback/$feedbackId/': {
      id: '/@{$org}/$project/feedback/$feedbackId/'
      path: '/feedback/$feedbackId'
      fullPath: '/@{$org}/$project/feedback/$feedbackId'
      preLoaderRoute: typeof AtChar123orgChar125ProjectFeedbackFeedbackIdIndexRouteImport
      parentRoute: typeof AtChar123orgChar125ProjectRouteRoute
    }
    '/@{$org}/$project/chat/$chatId/': {
      id: '/@{$org}/$project/chat/$chatId/'
      path: '/chat/$chatId'
      fullPath: '/@{$org}/$project/chat/$chatId'
      preLoaderRoute: typeof AtChar123orgChar125ProjectChatChatIdIndexRouteImport
      parentRoute: typeof AtChar123orgChar125ProjectRouteRoute
    }
    '/@{$org}/$project/feedback/board/new': {
      id: '/@{$org}/$project/feedback/board/new'
      path: '/feedback/board/new'
      fullPath: '/@{$org}/$project/feedback/board/new'
      preLoaderRoute: typeof AtChar123orgChar125ProjectFeedbackBoardNewRouteImport
      parentRoute: typeof AtChar123orgChar125ProjectRouteRoute
    }
    '/@{$org}/$project/feedback/board/$board/': {
      id: '/@{$org}/$project/feedback/board/$board/'
      path: '/feedback/board/$board'
      fullPath: '/@{$org}/$project/feedback/board/$board'
      preLoaderRoute: typeof AtChar123orgChar125ProjectFeedbackBoardBoardIndexRouteImport
      parentRoute: typeof AtChar123orgChar125ProjectRouteRoute
    }
    '/@{$org}/$project/feedback/board/$board/edit': {
      id: '/@{$org}/$project/feedback/board/$board/edit'
      path: '/feedback/board/$board/edit'
      fullPath: '/@{$org}/$project/feedback/board/$board/edit'
      preLoaderRoute: typeof AtChar123orgChar125ProjectFeedbackBoardBoardEditRouteImport
      parentRoute: typeof AtChar123orgChar125ProjectRouteRoute
    }
    '/@{$org}/$project/feedback/board/$board/@layout': {
      id: '/@{$org}/$project/feedback/board/$board/@layout'
      path: '/feedback/board/$board/@layout'
      fullPath: '/@{$org}/$project/feedback/board/$board/@layout'
      preLoaderRoute: typeof AtChar123orgChar125ProjectFeedbackBoardBoardAtlayoutRouteImport
      parentRoute: typeof AtChar123orgChar125ProjectRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AtChar123orgChar125ProjectRouteRouteChildren {
  AtChar123orgChar125ProjectIndexRoute: typeof AtChar123orgChar125ProjectIndexRoute
  AtChar123orgChar125ProjectChatAtlayoutRoute: typeof AtChar123orgChar125ProjectChatAtlayoutRoute
  AtChar123orgChar125ProjectChatIndexRoute: typeof AtChar123orgChar125ProjectChatIndexRoute
  AtChar123orgChar125ProjectDiscussionsIndexRoute: typeof AtChar123orgChar125ProjectDiscussionsIndexRoute
  AtChar123orgChar125ProjectFeedbackIndexRoute: typeof AtChar123orgChar125ProjectFeedbackIndexRoute
  AtChar123orgChar125ProjectFilesIndexRoute: typeof AtChar123orgChar125ProjectFilesIndexRoute
  AtChar123orgChar125ProjectRoadmapIndexRoute: typeof AtChar123orgChar125ProjectRoadmapIndexRoute
  AtChar123orgChar125ProjectUpdatesIndexRoute: typeof AtChar123orgChar125ProjectUpdatesIndexRoute
  AtChar123orgChar125ProjectFeedbackBoardNewRoute: typeof AtChar123orgChar125ProjectFeedbackBoardNewRoute
  AtChar123orgChar125ProjectChatChatIdIndexRoute: typeof AtChar123orgChar125ProjectChatChatIdIndexRoute
  AtChar123orgChar125ProjectFeedbackFeedbackIdIndexRoute: typeof AtChar123orgChar125ProjectFeedbackFeedbackIdIndexRoute
  AtChar123orgChar125ProjectFeedbackBoardsIndexRoute: typeof AtChar123orgChar125ProjectFeedbackBoardsIndexRoute
  AtChar123orgChar125ProjectFeedbackNewIndexRoute: typeof AtChar123orgChar125ProjectFeedbackNewIndexRoute
  AtChar123orgChar125ProjectFeedbackBoardBoardAtlayoutRoute: typeof AtChar123orgChar125ProjectFeedbackBoardBoardAtlayoutRoute
  AtChar123orgChar125ProjectFeedbackBoardBoardEditRoute: typeof AtChar123orgChar125ProjectFeedbackBoardBoardEditRoute
  AtChar123orgChar125ProjectFeedbackBoardBoardIndexRoute: typeof AtChar123orgChar125ProjectFeedbackBoardBoardIndexRoute
}

const AtChar123orgChar125ProjectRouteRouteChildren: AtChar123orgChar125ProjectRouteRouteChildren =
  {
    AtChar123orgChar125ProjectIndexRoute: AtChar123orgChar125ProjectIndexRoute,
    AtChar123orgChar125ProjectChatAtlayoutRoute:
      AtChar123orgChar125ProjectChatAtlayoutRoute,
    AtChar123orgChar125ProjectChatIndexRoute:
      AtChar123orgChar125ProjectChatIndexRoute,
    AtChar123orgChar125ProjectDiscussionsIndexRoute:
      AtChar123orgChar125ProjectDiscussionsIndexRoute,
    AtChar123orgChar125ProjectFeedbackIndexRoute:
      AtChar123orgChar125ProjectFeedbackIndexRoute,
    AtChar123orgChar125ProjectFilesIndexRoute:
      AtChar123orgChar125ProjectFilesIndexRoute,
    AtChar123orgChar125ProjectRoadmapIndexRoute:
      AtChar123orgChar125ProjectRoadmapIndexRoute,
    AtChar123orgChar125ProjectUpdatesIndexRoute:
      AtChar123orgChar125ProjectUpdatesIndexRoute,
    AtChar123orgChar125ProjectFeedbackBoardNewRoute:
      AtChar123orgChar125ProjectFeedbackBoardNewRoute,
    AtChar123orgChar125ProjectChatChatIdIndexRoute:
      AtChar123orgChar125ProjectChatChatIdIndexRoute,
    AtChar123orgChar125ProjectFeedbackFeedbackIdIndexRoute:
      AtChar123orgChar125ProjectFeedbackFeedbackIdIndexRoute,
    AtChar123orgChar125ProjectFeedbackBoardsIndexRoute:
      AtChar123orgChar125ProjectFeedbackBoardsIndexRoute,
    AtChar123orgChar125ProjectFeedbackNewIndexRoute:
      AtChar123orgChar125ProjectFeedbackNewIndexRoute,
    AtChar123orgChar125ProjectFeedbackBoardBoardAtlayoutRoute:
      AtChar123orgChar125ProjectFeedbackBoardBoardAtlayoutRoute,
    AtChar123orgChar125ProjectFeedbackBoardBoardEditRoute:
      AtChar123orgChar125ProjectFeedbackBoardBoardEditRoute,
    AtChar123orgChar125ProjectFeedbackBoardBoardIndexRoute:
      AtChar123orgChar125ProjectFeedbackBoardBoardIndexRoute,
  }

const AtChar123orgChar125ProjectRouteRouteWithChildren =
  AtChar123orgChar125ProjectRouteRoute._addFileChildren(
    AtChar123orgChar125ProjectRouteRouteChildren,
  )

interface AtChar123orgChar125RouteRouteChildren {
  AtChar123orgChar125ProjectRouteRoute: typeof AtChar123orgChar125ProjectRouteRouteWithChildren
  AtChar123orgChar125SettingsRoute: typeof AtChar123orgChar125SettingsRoute
  AtChar123orgChar125IndexRoute: typeof AtChar123orgChar125IndexRoute
}

const AtChar123orgChar125RouteRouteChildren: AtChar123orgChar125RouteRouteChildren =
  {
    AtChar123orgChar125ProjectRouteRoute:
      AtChar123orgChar125ProjectRouteRouteWithChildren,
    AtChar123orgChar125SettingsRoute: AtChar123orgChar125SettingsRoute,
    AtChar123orgChar125IndexRoute: AtChar123orgChar125IndexRoute,
  }

const AtChar123orgChar125RouteRouteWithChildren =
  AtChar123orgChar125RouteRoute._addFileChildren(
    AtChar123orgChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  RouteRoute: RouteRoute,
  AtChar123orgChar125RouteRoute: AtChar123orgChar125RouteRouteWithChildren,
  Blank404Route: Blank404Route,
  BlankSignInRoute: BlankSignInRoute,
  BlankSignOutRoute: BlankSignOutRoute,
  CreateAtlayoutRoute: CreateAtlayoutRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  CreateProjectIndexRoute: CreateProjectIndexRoute,
  CreateTeamIndexRoute: CreateTeamIndexRoute,
  ProfileUsernameIndexRoute: ProfileUsernameIndexRoute,
  ProfileSettingsIndexRoute: ProfileSettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
