// biome-ignore-all format: generated
// This file is auto-generated by kitcn migrate create.
// Do not edit manually.

import { defineMigrationSet } from 'kitcn/orm';

import { migration as migration_0 } from './20260729_215959_rename_org_editor_to_moderator';
import { migration as migration_1 } from './20260729_220000_rename_editor_invitations';
import { migration as migration_2 } from './20260729_220001_downgrade_system_editor_users';
import { migration as migration_3 } from './20260729_220002_downgrade_system_editor_profiles';
import { migration as migration_4 } from './20260729_220003_simplify_project_members';
import { migration as migration_5 } from './20260825_000000_backfill_account_issuer';

export const migrations = defineMigrationSet([
	migration_0,
	migration_1,
	migration_2,
	migration_3,
	migration_4,
	migration_5,
]);
